name: Prettier for Java Code

on: [push, pull_request]

jobs:
  cleanup_tasks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: Prettify the Java Code
      uses: lwerner-lshigh/prettier_action_java@v1.1.1
      with:
        prettier_options: '--no-semi --write */*.java'
        branch: ${{ github.head_ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.WORKFLOW }}
